# Create Anything App - Netlify Configuration
# Production deployment settings

[build]
  base = "apps/web"
  command = "cd ../.. && npm install --legacy-peer-deps && cd apps/web && npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "22.0.0"
  NPM_FLAGS = "--legacy-peer-deps"

# API proxy to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
