# Create Anything App - Netlify Configuration
# Production deployment settings

[build]
  base = "apps/web"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.11.0"

# API proxy to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
