[build]
  base = "apps/web"
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Ignore mobile app during build
[build.ignore]
  paths = ["apps/mobile/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200